name: Update Repository Data

on:
  schedule:
    - cron: '50 19 * * *'  # Exécution tous les jours à 20h50 heure de Paris en été
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

permissions:
  contents: write  # Donne au GITHUB_TOKEN les permissions d'écriture
  issues: read     # Donne accès aux issues du dépôt (si besoin)

jobs:
  update-repo-data:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2: Vérifier le quota de l'API
      - name: Check API rate limit
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit

      # Étape 3: Récupérer la liste de tous les dépôts de l'utilisateur
      - name: Fetch repository data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/user/repos?per_page=100&type=public > repos.json

      # Étape 4: Afficher le contenu de repos.json
      - name: Afficher le contenu de repos.json
        run: cat repos.json

      # Étape 5: Ajouter le fichier JSON au dépôt et le committer sur la branche 'test-workflows'
      - name: Commit repository data
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action Bot"
          git add repos.json
          git commit --allow-empty -m "Mise à jour des données des dépôts"
          git push origin test-workflows
