name: Update Repository Data

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution tous les jours à 0h00 UTC
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

permissions:
  contents: write  # Donne au PAT les permissions d'écriture
  issues: read     # Donne accès aux issues du dépôt (si besoin)

jobs:
  update-repo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch repository data dans le répertoire de travail
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/user/repos?per_page=100&type=public > $GITHUB_WORKSPACE/repos.json
          ls -lh $GITHUB_WORKSPACE/repos.json
          cat $GITHUB_WORKSPACE/repos.json  # Vérifier le contenu du fichier après récupération

      # Ajouter un timestamp dans repos.json
      - name: Modifier repos.json avec un timestamp
        run: |
          echo "Dernière mise à jour: $(date)" >> $GITHUB_WORKSPACE/repos.json
          cat $GITHUB_WORKSPACE/repos.json  # Vérifier après ajout du timestamp

      # Commit et push des données
      - name: Commit repository data
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action Bot"
          git add repos.json
          git commit -m "Mise à jour des données des dépôts"
          git push origin test-workflows
